// List categories = <String>null;
Map<String, List<String>> categoryDetails = <String, List<String>>{
  'Mathematics': null,
  'Physics': null,
  'Chemistry': null,
  'Biology': null,
  'Engineering': [
    'CSE',
    'ECE',
    'IT',
    'Mech',
    'Chem',
    'EEE',
    'Civil',
    'Biotech',
    'Petroleum'
  ],
  'Law': null,
  'Religious': [
    'Hinduism',
    'Islam',
    'Christianity',
    'Budhism',
    'Jainism',
  ],
  'Poetry': null,
  'Philosophy': null,
  'Novel': [
    'Horror',
    'Fiction',
    'Crime',
    'Thriller',
    'Romance',
    'Adventure',
    'Biography',
    'Art',
    'Comics',
  ],
  'History': null,
  'Medicine': [
    'Anatomy',
    'Biochemistry',
    'Physiology',
    'Pathology',
    'Microbiology',
    'Pharmology',
    'Forensic Medicine',
    'ENT',
    'Opthamology',
    'Community Medicine',
    'General Medicine',
    'General Surgery',
    'Pediatric',
    'Gynecology',
    'Obstetrics',
    'Orthopedics',
    'Derma Venero Lepra',
    'Radiology',
    'Psychiatry',
    'Anesthesiology',
    'Pulmonary Medicine',
    'Anesthesia',
    'Neurosurgery',
    'Cardiology',
    'Neurology',
    'Medical Genetics'
  ]
};

List<String> categoryImages = [
  'accounting',
  'art',
  'biography',
  'biology',
  'calculator',
  'chemistry',
  'comic',
  'engineering',
  'history',
  'law',
  'medicine',
  'novel',
  'philosophy',
  'poetry',
  'religious'
];
